name: Deploy

on: push



jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-python@v1
     - run: |
         pip install -U pip
         pip install poetry
         poetry install
       env:
         POETRY_VIRTUALENVS_CREATE: false
